### ISSUE TITLE
ReadConfigFile的bug

### ISSUE THREAD

**Issue by zhouwenbin00** [winjeg/go-commons#7]
这个参数没使用
![image](https://user-images.githubusercontent.com/38801711/120147011-946b5d80-c218-11eb-8a07-42993a0f7e8e.png)

**Comment by winjeg** [comment]
Thank you for your advice.
FIXED in commit https://github.com/winjeg/go-commons/commit/191c33f38b681f9186e553b508e0d93b1400633f.

**Comment by winjeg** [comment]
> 这个参数没使用
> ![image](https://user-images.githubusercontent.com/38801711/120147011-946b5d80-c218-11eb-8a07-42993a0f7e8e.png)

Thank you for your advice.
FIXED in commit https://github.com/winjeg/go-commons/commit/191c33f38b681f9186e553b508e0d93b1400633f.
